---
region: 'eu-west-2'

account_id: "579878096224"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

infrastructure_events_bucket: "tobyclemson-open-source"

domain_name: "infrablocks.click"
public_zone_id: "Z08829023L5IPIQBJOX63"
private_zone_id: 'Z0211739BXR21FNN139O'
subdomain: "api.%{hiera('deployment_identifier')}"
